# pyproject.toml

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "addition"
version = "0.1.0"
description = "A simple addition function"
authors = [
    { name = "Your Name", email = "your-email@example.com" }
]
dependencies = []
